# Generated by Django 3.2.5 on 2021-08-02 20:01

from django.db import migrations, models
import django.db.models.deletion
import item.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(default='undefined', max_length=14)),
                ('price', models.FloatField(default=0)),
                ('calories', models.IntegerField(blank=True, default=100)),
                ('id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(default='def.jpg', upload_to=item.models.item_media_path)),
                ('spicy', models.IntegerField(default=1)),
                ('description', models.CharField(default='', max_length=250)),
                ('category', models.CharField(choices=[('Pizza', 'pizza'), ('Soups', 'soups'), ('Drinks', 'drinks'), ('Others', 'others')], default='others', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('unit', models.CharField(choices=[('g', 'grams'), ('pc', 'piece'), ('ml', 'milliliters'), (' ', 'undefined'), ('tsp', 'table_spoon'), ('cup', 'cup')], default='undefined', max_length=100)),
                ('quantity', models.CharField(max_length=8)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='item.item')),
            ],
        ),
    ]
