# Generated by Django 3.2.5 on 2021-08-01 10:08

from django.db import migrations, models
import django.db.models.deletion
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='calories',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(default='def.jpg', upload_to=item.models.item_media_path),
        ),
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item.ingredient'),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='undefined', max_length=14),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='spicy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
