# Generated by Django 3.2.5 on 2021-08-03 19:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='undefined', max_length=20),
        ),
    ]
